export const characters = {
  'Edelgard':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Peach Sorbet',
     'Vegetable Pasta Salad',
     'Onion Gratin Soup',
     'Vegetable Stir-Fry',
     'Fish and Bean Soup',
     'Fish Sandwich',
     'Sauteed Pheasant and Eggs' ],
  'Hubert':
   [ 'Two-Fish Saute',
     'Sauteed Jerky',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables',
     'Gautier Cheese Gratin',
     'Cabbage and Herring Stew' ],
  'Ferdinand':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Daphnel Stew',
     'Vegetable Pasta Salad',
     'Onion Gratin Soup',
     'Vegetable Stir-Fry',
     'Grilled Herring',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Bourgeois Pike',
     'Sauteed Pheasant and Eggs' ],
  'Linhardt':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Daphnel Stew',
     'Onion Gratin Soup',
     'Fish and Bean Soup',
     'Garreg Mach Meat Pie',
     'Gautier Cheese Gratin' ],
  'Caspar':
   [ 'Sweet Bun Trio',
     'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Pasta Salad',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Sauteed Jerky',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie' ],
  'Bernadetta':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Peach Sorbet',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Pasta Salad',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Fruit and Herring Tart',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Cheesy Verona Stew' ],
  'Dorothea':
   [ 'Saghert and Cream',
     'Peach Sorbet',
     'Vegetable Pasta Salad',
     'Onion Gratin Soup',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Garreg Mach Meat Pie',
     'Gautier Cheese Gratin' ],
  'Petra':
   [ 'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Grilled Herring',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Sauteed Jerky',
     'Spicy Fish and Turnip Stew',
     'Super-Spicy Fish Dango',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables' ],
  'Dimitri':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Onion Gratin Soup',
     'Sauteed Jerky',
     'Cheesy Verona Stew',
     'Gautier Cheese Gratin' ],
  'Dedue':
   [ 'Daphnel Stew',
     'Onion Gratin Soup',
     'Vegetable Stir-Fry',
     'Grilled Herring',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Sauteed Jerky',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Pickled Seafood and Vegetables' ],
  'Felix':
   [ 'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Two-Fish Saute',
     'Sauteed Jerky',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie',
     'Gautier Cheese Gratin' ],
  'Ashe':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Vegetable Pasta Salad',
     'Fish and Bean Soup',
     'Fish Sandwich',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute' ],
  'Sylvain':
   [ 'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Fish Sandwich',
     'Two-Fish Saute',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie',
     'Cheesy Verona Stew' ],
  'Mercedes':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Vegetable Pasta Salad',
     'Onion Gratin Soup',
     'Grilled Herring',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Two-Fish Saute' ],
  'Annette':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Vegetable Pasta Salad',
     'Onion Gratin Soup',
     'Vegetable Stir-Fry',
     'Grilled Herring',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Two-Fish Saute',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Pickled Seafood and Vegetables' ],
  'Ingrid':
   [ 'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Pasta Salad',
     'Grilled Herring',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango' ],
  'Claude':
   [ 'Pheasant Roast with Berry Sauce',
     'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Onion Gratin Soup',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Bourgeois Pike',
     'Sauteed Jerky',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie',
     'Cheesy Verona Stew',
     'Gautier Cheese Gratin',
     'Cabbage and Herring Stew' ],
  'Lorenz':
   [ 'Saghert and Cream',
     'Daphnel Stew',
     'Onion Gratin Soup',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Garreg Mach Meat Pie',
     'Cabbage and Herring Stew' ],
  'Raphael':
   [ 'Pheasant Roast with Berry Sauce',
     'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Country-Style Red Turnip Plate',
     'Fish and Bean Soup',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Sauteed Jerky',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables',
     'Gautier Cheese Gratin' ],
  'Ignatz':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Vegetable Pasta Salad',
     'Vegetable Stir-Fry',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie',
     'Cabbage and Herring Stew' ],
  'Lysithea':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Pickled Rabbit Skewers',
     'Derdriu-Style Fried Pheasant',
     'Two-Fish Saute' ],
  'Marianne':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Peach Sorbet',
     'Vegetable Pasta Salad',
     'Onion Gratin Soup',
     'Vegetable Stir-Fry',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Cheesy Verona Stew',
     'Cabbage and Herring Stew' ],
  'Hilda':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Peach Sorbet',
     'Derdriu-Style Fried Pheasant',
     'Country-Style Red Turnip Plate',
     'Fish and Bean Soup',
     'Fisherman’s Bounty',
     'Two-Fish Saute',
     'Cheesy Verona Stew',
     'Gautier Cheese Gratin' ],
  'Leonie':
   [ 'Beast Meat Teppanyaki',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Onion Gratin Soup',
     'Vegetable Stir-Fry',
     'Grilled Herring',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables',
     'Cabbage and Herring Stew' ],
  'Seteth':
   [ 'Daphnel Stew',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Pasta Salad',
     'Grilled Herring',
     'Fruit and Herring Tart',
     'Fish Sandwich',
     'Bourgeois Pike',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables' ],
  'Flayn':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Onion Gratin Soup',
     'Country-Style Red Turnip Plate',
     'Grilled Herring',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables',
     'Cabbage and Herring Stew' ],
  'Hanneman':
   [ 'Peach Sorbet',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Pasta Salad',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Super-Spicy Fish Dango',
     'Garreg Mach Meat Pie',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables',
     'Gautier Cheese Gratin',
     'Cabbage and Herring Stew' ],
  'Manuela':
   [ 'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Stir-Fry',
     'Fish and Bean Soup',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Sauteed Jerky',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie',
     'Cabbage and Herring Stew' ],
  'Gilbert':
   [ 'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Pasta Salad',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Grilled Herring',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Garreg Mach Meat Pie',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables',
     'Cabbage and Herring Stew' ],
  'Alois':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Onion Gratin Soup',
     'Grilled Herring',
     'Fish and Bean Soup',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Pickled Seafood and Vegetables' ],
  'Catherine':
   [ 'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Onion Gratin Soup',
     'Country-Style Red Turnip Plate',
     'Grilled Herring',
     'Fruit and Herring Tart',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Super-Spicy Fish Dango',
     'Garreg Mach Meat Pie',
     'Cheesy Verona Stew',
     'Pickled Seafood and Vegetables',
     'Gautier Cheese Gratin',
     'Cabbage and Herring Stew' ],
  'Shamir':
   [ 'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Vegetable Pasta Salad',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Sauteed Jerky',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs' ],
  'Cyril':
   [ 'Pheasant Roast with Berry Sauce',
     'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Pasta Salad',
     'Vegetable Stir-Fry',
     'Fish and Bean Soup',
     'Two-Fish Saute',
     'Sauteed Jerky',
     'Sauteed Pheasant and Eggs' ],
  'Jeritza':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Gronder Meat Skewers',
     'Onion Gratin Soup',
     'Grilled Herring',
     'Fish and Bean Soup',
     'Fisherman’s Bounty',
     'Two-Fish Saute',
     'Cabbage and Herring Stew',
     'Small Fish Skewers',
     'Fried Crayfish' ],
  'Anna':
   [ 'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Derdriu-Style Fried Pheasant',
     'Vegetable Pasta Salad',
     'Bourgeois Pike',
     'Sauteed Jerky',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Sauteed Pheasant and Eggs',
     'Pickled Seafood and Vegetables',
     'Fried Crayfish' ],
  'Yuri':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Onion Gratin Soup',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Grilled Herring',
     'Fish and Bean Soup',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Two-Fish Saute',
     'Sauteed Jerky' ],
  'Balthus':
   [ 'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Fisherman’s Bounty',
     'Sauteed Jerky',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Garreg Mach Meat Pie',
     'Cheesy Verona Stew',
     'Gautier Cheese Gratin',
     'Cabbage and Herring Stew' ],
  'Constance':
   [ 'Saghert and Cream',
     'Sweet Bun Trio',
     'Pheasant Roast with Berry Sauce',
     'Peach Sorbet',
     'Vegetable Pasta Salad',
     'Fruit and Herring Tart',
     'Two-Fish Saute',
     'Bourgeois Pike',
     'Sauteed Pheasant and Eggs' ],
  'Hapi':
   [ 'Pheasant Roast with Berry Sauce',
     'Beast Meat Teppanyaki',
     'Pickled Rabbit Skewers',
     'Daphnel Stew',
     'Gronder Meat Skewers',
     'Derdriu-Style Fried Pheasant',
     'Onion Gratin Soup',
     'Country-Style Red Turnip Plate',
     'Vegetable Stir-Fry',
     'Fish and Bean Soup',
     'Fisherman’s Bounty',
     'Fish Sandwich',
     'Sauteed Jerky',
     'Spicy Fish and Turnip Stew',
     'Sweet and Salty Whitefish Saute',
     'Super-Spicy Fish Dango',
     'Sauteed Pheasant and Eggs',
     'Pickled Seafood and Vegetables',
     'Cabbage and Herring Stew',
     'Small Fish Skewers',
     'Fried Crayfish' ] 
}
